<?php
/**
 * Copyright © Carriyo. All rights reserved.
 * https://www.carriyo.com | info@carriyo.com
 */
// @codingStandardsIgnoreFile

$_shipment = $block->getShipment();
$_order = $block->getOrder();
$trackCollection = $_order->getTracksCollection($_shipment->getId());
?>
<?php if ($_shipment && $_order && $trackCollection): ?>
    <br />
    <table class="shipment-track">
        <thead>
        <tr>
            <th><?= __('Shipped By') ?></th>
            <th><?= __('Tracking Number') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($trackCollection as $_item): ?>
            <?php $trackingUrl = (string)$_item->getDescription(); ?>
            <tr>
                <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
                <td>
                    <?php if (filter_var($trackingUrl, FILTER_VALIDATE_URL)): ?>
                        <a href="<?= $block->escapeUrl($trackingUrl) ?>" target="_blank" rel="noopener noreferrer">
                            <?= $block->escapeHtml($_item->getNumber()) ?>
                        </a>
                    <?php else: ?>
                        <?= $block->escapeHtml($_item->getNumber()) ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<?php endif; ?>
